image: $CI_REGISTRY_IMAGE

stages:
  - docker
  - pages
  - lint
  - test
  - build
  - publish

docker:
  stage: docker
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker
  services:
    - $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:dind
  tags:
    - dind
    - privileged
  variables:
    TAG: "$CI_REGISTRY_IMAGE"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $TAG || true
    - docker build --pull --cache-from $TAG --tag $TAG --file .Dockerfile .
    - docker push $TAG
  only:
  - master

pages:
  stage: pages
  before_script:
    - COVERAGE=y python3 setup.py install
    - export LD_LIBRARY_PATH=/usr/local/lib
    - python3 -m pytest tests
  script:
    - lcov --capture --no-external --base-directory . --directory build/temp.* --output-file coverage.info
    - genhtml coverage.info --output-directory public/coverage-c
  artifacts:
    when: on_success
    paths:
      - public
  only:
  - master

include:
  - remote: "https://gitlab.nic.cz/turris/foris-controller/packages/-/raw/master/templates/python/base.yml"
  - remote: "https://gitlab.nic.cz/turris/foris-controller/packages/-/raw/master/templates/python/linters.yml"
  - remote: "https://gitlab.nic.cz/turris/foris-controller/packages/-/raw/master/templates/python/test_and_coverage.yml"
  - remote: "https://gitlab.nic.cz/turris/foris-controller/packages/-/raw/master/templates/python/build_and_publish.yml"

lint::python::tox:
  variables:
    IMAGE: registry.nic.cz/turris/foris-ci/ci-tests

test::python:
  image: registry.nic.cz/turris/foris-ci/ci-tests
  parallel:
    matrix:
      - PYTHON: ['3.9.16', '3.10.11', '3.11.3']
  before_script:
    - pyenv local $PYTHON

build::python:
  image: registry.nic.cz/turris/foris-ci/ci-tests
  parallel:
    matrix:
      - PYTHON: ['3.9.16', '3.10.11', '3.11.3']
  before_script:
    - pyenv local $PYTHON
